name: 'Deploy Service ECS'
description: 'Queima Labs DevOps Stack - Deploy Microservice - services no ECS da AWS'
inputs:
  ecs-cluster:  # ID Service
    description: Cluster name to be deploy to
    required: true
    default: 'queima-microservice-dev'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:           
    - name: Get Environment names
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment-acronym }}
        CONFIG: ${{ inputs.config }}
      run: |
        source $(echo CONFIG | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]")
        sh config/environment.config.sh
        cat .env
    
    - name: Configure NPM
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
      run: |
        cat <<EOF > .npmrc
        @queimadiaria:registry=https://npm.pkg.github.com/
        //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
        EOF


    - name: Build, tag, and push image to Amazon ECR
      shell: bash
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build \
          --build-arg NODE_ENV=development \
          --build-arg NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} \
          --build-arg NEW_RELIC_APP_NAME=${{ inputs.service-name }}-${{ inputs.service-stage }} \
          -t $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG"

    - name: Get Task Definition
      shell: bash
      run: |
        aws ecs describe-task-definition \
            --task-definition "task-${SERVICE_NAME}" \
            --region "us-east-1" \
            --query taskDefinition | \
          jq --arg img "${SERVICE_NAME}" \
            '.containerDefinitions[0].name = $img' > taskDefinition.json
          
        cat taskDefinition.json

        CLUSTER=$(aws ecs list-clusters | \
          jq ".clusterArns[]" -r | \
          cut -d "/" -f2 | \
          grep ${{ inputs.stage }})

        echo "CLUSTER=$CLUSTER" >> $GITHUB_ENV

